### ISSUE TITLE
RC config file support for programmatic usage

### ISSUE THREAD

**Issue by adamhamlin** [pinojs/pino-pretty#429]
Best I can tell, the rc files are only loaded for CLI usage (i.e., going through `bin.js`). Any plans to extend that to programmatic usage?

https://github.com/pinojs/pino-pretty/blob/849f0fc907adc3df30e7290b7fc091a055a30e51/bin.js#L23-L32

**Comment by jsumners** [comment]
There are not any plans to do so. In my opinion, I think the readme is rather clear that this module is not meant for production use cases and adding such support would make it easier to use in unsupported contexts. The rc file support that is currently included is provided for CLI usage where providing options on each invocation is quite cumbersome otherwise. This is a common feature in CLI applications (pino-pretty's primary purpose).

I would say that if loading rc files is desired in programmatic usage, then it is the responsibility of the app.

**Comment by adamhamlin** [comment]
Better late than never. Opened https://github.com/pinojs/pino-pretty/pull/475
